### ISSUE TITLE
Confusion regarding your repository

### ISSUE THREAD

**Issue by wadhwasahil** [evamy/learning_nlp#1]
Hi
I am Sahil Wadhwa. What exactly are trying to implement in this repository?

:smiling_imp:

**Comment by antiDigest** [comment]
Hello @wadhwasahil ,

I'm implementing anything and everything worth learning in NLP.

Thanks
Antriksh

**Comment by wadhwasahil** [comment]
:+1:  Keep me informed

**Comment by antiDigest** [comment]
Hey @wadhwasahil,

I updated the motivation to the repository. It'd be great if you'd like to contribute.

Thanks
